### ISSUE TITLE
Offer more detail

### ISSUE THREAD

**Issue by Fishhao123** [ammarali32/SeatBeltDetection#1]
Hi, good work! I tested your model on single images, and it can function. Could you offer some details about your work? Like your training process and the dataset you used. Thanks!

**Comment by ammarali32** [comment]
Hi, It is not the final work it is just for my students the final work is
much better. I applied a paper about my work and it has been accepted. I
think it will be published in the next month.
i

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by zhcv** [comment]
@ammarali32 HI，Has your paper been published?

**Comment by ammarali32** [comment]
> @ammarali32 HI，Has your paper been published?

Hi, yes it did here is a link to the paper https://ieeexplore.ieee.org/document/9087474

**Comment by zhcv** [comment]
> > @ammarali32 HI，Has your paper been published?
> 
> Hi, yes it did here is a link to the paper https://ieeexplore.ieee.org/document/9087474

HI, Could you offer your training process and the dataset you used. Thanks!

**Comment by ammarali32** [comment]
> > > @ammarali32 HI，Has your paper been published?
> > 
> > 
> > Hi, yes it did here is a link to the paper https://ieeexplore.ieee.org/document/9087474
> 
> HI, Could you offer your training process and the dataset you used. Thanks!

No, I am sorry but the work is for the industry so I can't provide it. but if you had questions about the learning please look through AlexeyAB repository and build it. It will facilitate the training process for you and you can easily modify the Yolo architecture

**Comment by Fishhao123** [comment]
> > > @ammarali32 HI，Has your paper been published?
> > 
> > 
> > Hi, yes it did here is a link to the paper https://ieeexplore.ieee.org/document/9087474
> 
> HI, Could you offer your training process and the dataset you used. Thanks!

Actually, I labeled some bounding boxes on YawDD dataset by myself, and I trained YOLOv3 model on this, it could work.
